version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3002"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
      - NEXT_PUBLIC_APPWRITE_DATABASE_ID=${NEXT_PUBLIC_APPWRITE_DATABASE_ID}
      - NEXT_PUBLIC_APPWRITE_WAITLIST_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_WAITLIST_COLLECTION_ID}
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true